test_type: deterministic
dataset:
  name: australian_electricity_demand
  path: benchmarking_pipeline/datasets/australian_electricity_demand
  frequency: D
  forecast_horizon: 5
  split_ratio: [0.8, 0.1, 0.1]
  normalize: false
  handle_missing: interpolate
  chunks: 2
model:
  # Running all models with automatic variant detection
  # Format: "model_name" - system automatically detects optimal variant based on dataset
  # Anyvariate models can handle both variants within the same implementation
  # Non-anyvariate models route to separate univariate/multivariate folders based on dataset properties
  name: ["arima", "lstm", "svr", "theta", "xgboost", "prophet", "random_forest", "seasonal_naive", 
         "tabpfn", "deepar", "chronos", "moment", "lagllama", "toto", "moirai", "moirai_moe", 
         "timesfm", "croston_classic", "exponential_smoothing", "tiny_time_mixer"]

  parameters:
    tiny_time_mixer:
      prediction_length: [40]  # necessary - used in model initialization
    moment:
      model_path: ['AutonLab/MOMENT-1-large']  # necessary - used in model initialization
      context_length: [512]  # necessary - used in model initialization
      fine_tune_epochs: [0]  # necessary - used in model initialization
      batch_size: [8]  # necessary - used in model initialization
      learning_rate: [0.0001]  # necessary - used in model initialization
      prediction_length: [40]  # necessary - used in model initialization
    lagllama:
      prediction_length: [100]  # necessary - used in model initialization
      context_length: [4]  # necessary - used in model initialization
      num_samples: [5]  # necessary - used in model initialization
      batch_size: [4]  # necessary - used in model initialization
      target_cols: ['y']  # necessary - used in model initialization
    timesfm:
      per_core_batch_size: [2]  # necessary - used in model initialization
      horizon_len: [40]  # necessary - used in model initialization
      num_layers: [2]  # necessary - used in model initialization
      context_len: [2]  # necessary - used in model initialization
      use_positional_embedding: [False]  # necessary - used in model initialization
      target_cols: ['y']  # necessary - used in model initialization
    tabpfn:
      allow_large_cpu_dataset: [True]  # necessary - used in model initialization
      max_sequence_length: [32]  # necessary - used in model initialization
      prediction_length: [40]  # necessary - used in model initialization
      target_cols: ['y']  # unnecessary - removed default values, not used in tabpfn model
    chronos:
      model_size: ['small']  # necessary - used in model initialization
      context_length: [8]  # necessary - used in model initialization
      num_samples: [5]  # necessary - used in model initialization
      prediction_length: [40]  # necessary - used in model initialization
      target_cols: ['y']  # unnecessary - removed default values, not used in chronos model
    xgboost:
      lookback_window: [10]  # necessary - used in model initialization
      forecast_horizon: [10]  # necessary - used in model initialization
      n_estimators: [10]  # necessary - used in model initialization
      max_depth: [5]  # necessary - used in model initialization
      learning_rate: [0.1]  # necessary - used in model initialization
      random_state: [42]  # necessary - used in model initialization
      n_jobs: [-1]  # necessary - used in model initialization
      target_cols: ['y']  # necessary - used in model initialization
    prophet:
      seasonality_mode: ["additive"]  # necessary - used in model initialization
      changepoint_prior_scale: [0.05]  # necessary - used in model initialization
      seasonality_prior_scale: [10.0]  # necessary - used in model initialization
      yearly_seasonality: [false]  # necessary - used in model initialization
      weekly_seasonality: [false]  # necessary - used in model initialization
      daily_seasonality: [false]  # necessary - used in model initialization
      target_cols: ['y']  # unnecessary - removed default values, not used in prophet model
    lstm:
      units: [32]  # necessary - used in model initialization
      layers: [1]  # necessary - used in model initialization
      dropout: [0.1]  # necessary - used in model initialization
      learning_rate: [0.01, 1.0]  # necessary - used in model initialization
      batch_size: [32]  # necessary - used in model initialization
      epochs: [20]  # necessary - used in model initialization
      sequence_length: [10]  # necessary - used in model initialization
      target_cols: ["y"]  # unnecessary - removed default values, not used in lstm model
      loss_functions: ["mae"]  # necessary - used in base model
      primary_loss: ["mae"]  # necessary - used in base model
      forecast_horizon: [50]  # necessary - used in base model
    random_forest:
      lookback_window: [50, 100]  # necessary - used in model initialization
      forecast_horizon: [50]  # necessary - used in base model
      n_estimators: [10, 50]  # necessary - used in model initialization
      max_depth: [3, 7]  # necessary - used in model initialization
      random_state: [42]  # necessary - used in model initialization
      n_jobs: [-1]  # necessary - used in model initialization
      target_cols: ["y"]  # unnecessary - removed default values, not used in random_forest model
    exponential_smoothing:
      trend: ["none", "add"]  # necessary - used in model initialization
      seasonal: ["none", "add", "mul"]  # necessary - used in model initialization
      seasonal_periods: [7]  # necessary - used in model initialization
      damped_trend: [false]  # necessary - used in model initialization
      forecast_horizon: [50]  # necessary - used in base model
      target_cols: ["y"]  # unnecessary - removed default values, not used in exponential_smoothing model
    svr:
      kernel: ["rbf", "linear"]  # necessary - used in model initialization
      C: [0.1, 1.0, 10.0]  # necessary - used in model initialization
      epsilon: [0.01, 0.1, 0.2]  # necessary - used in model initialization
      gamma: ["scale", "auto"]  # necessary - used in model initialization
      lookback_window: [50, 100]  # necessary - used in model initialization
      forecast_horizon: [50]  # necessary - used in base model
      max_iter: [1000]  # necessary - used in model initialization
      random_state: [42]  # necessary - used in model initialization
      target_cols: ["y"]  # unnecessary - removed default values, not used in svr model
    arima:
      p: [0, 1, 2]  # necessary - used in model initialization
      d: [0, 1]  # necessary - used in model initialization
      q: [0, 1, 2]  # necessary - used in model initialization
      s: [2, 4]  # necessary - used in model initialization
      maxlags: [10]  # unnecessary - not used in arima model
      target_cols: ["y"]  # unnecessary - removed default values, not used in arima model
      loss_functions: ["mae"]  # necessary - used in base model
      primary_loss: ["mae"]  # necessary - used in base model
      forecast_horizon: [50]  # necessary - used in base model
    theta:
      sp: [1, 2, 3]  # necessary - used in model initialization
      forecast_horizon: [10]  # necessary - used in base model
      method: ["additive"]  # unnecessary - not used in theta model
      target_cols: ["y"]  # unnecessary - removed default values, not used in theta model
      loss_functions: ["mae"]  # necessary - used in base model
      primary_loss: ["mae"]  # necessary - used in base model
    moirai:
      model_name: ["moirai"]  # necessary - used in model initialization
      size: ["small"]  # necessary - used in model initialization
      pdt: [900]  # necessary - used in model initialization
      psz: [32]  # necessary - used in model initialization
      bsz: [8]  # necessary - used in model initialization
      num_samples: [5]  # necessary - used in model initialization
      target_cols: ['y']  # unnecessary - removed default values, not used in moirai model
    moirai_moe:
      model_name: ["moirai_moe"]  # necessary - used in model initialization
      size: ["small"]  # necessary - used in model initialization
      pdt: [900]  # necessary - used in model initialization
      psz: [32]  # necessary - used in model initialization
      bsz: [8]  # necessary - used in model initialization
      num_samples: [5]  # necessary - used in model initialization
      target_cols: ['y']  # unnecessary - removed default values, not used in moirai_moe model
    toto:
      model_name: ["toto"]  # necessary - used in model initialization
      prediction_length: [900]  # necessary - used in model initialization
      num_samples: [40]  # necessary - used in model initialization
      samples_per_batch: [40]  # necessary - used in model initialization
      target_cols: ["y"]  # unnecessary - removed default values, not used in toto model
    seasonal_naive:
      sp: [7, 14]  # necessary - used in model initialization
      forecast_horizon: [50]  # necessary - used in base model
      target_cols: ["y"]  # unnecessary - removed default values, not used in seasonal_naive model
    deepar:
      prediction_length: [40]  # necessary - used in model initialization
      context_length: [20]  # necessary - used in model initialization
      num_samples: [5]  # necessary - used in model initialization
      batch_size: [8]  # necessary - used in model initialization
      epochs: [1]  # necessary - used in model initialization
      learning_rate: [0.001]  # necessary - used in model initialization
      target_cols: ['y']  # unnecessary - removed default values, not used in deepar model

evaluation:
  type: deterministic
  metrics: [mae, rmse] 