test_type: deterministic
dataset:
  name: "univariate/*"
  split_ratio: [0.8, 0.1, 0.1]
  normalize: false
  handle_missing: interpolate
  chunks: 1

model:

  ############## Statistical Models ##############
  exponential_smoothing:
    trend: ["add", null]
    seasonal: [null]
    seasonal_periods: [null]
    damped_trend: [false, true]
  
  seasonal_naive:
    sp: [24]
  
  croston_classic:
    alpha: [0.1, 0.3, 0.5]
    gamma: [0.1, 0.3, 0.5]
  
  theta: 
    sp: [12]

  arima:
    p: [1, 2]
    d: [1]
    q: [1, 2]
    s: [2]

  ############## Machine Learning Models ##############
  xgboost:
    lookback_window: [30]
    n_estimators: [200]
    max_depth: [4]
    learning_rate: [0.05]
    subsample: [0.9]
    colsample_bytree: [0.9]
    random_state: [42]
    n_jobs: [1]
  
  random_forest:
    lookback_window: [50]
    n_estimators: [10]
    max_depth: [2]
    random_state: [42]
    n_jobs: [1]
    forecast_horizon: [50]

  svr:
    training_loss: ["mae"]
    kernel: ["rbf"]
    C: [1.0]
    epsilon: [0.1]
    gamma: ["scale"]
    lookback_window: [50]
    forecast_horizon: [10]

  prophet:
    seasonality_mode: ["additive"]
    changepoint_prior_scale: [0.05]
    seasonality_prior_scale: [10.0]
    yearly_seasonality: [true]
    weekly_seasonality: [true]
    daily_seasonality: [false]

  ############## Deep Learning Models ##############
  lstm:
    units: [32]
    layers: [1]
    dropout: [0.1]
    learning_rate: [0.01]
    batch_size: [32]
    epochs: [100]
    sequence_length: [10]
    training_loss: ["mae"]
    forecast_horizon: [10]
  
  # Foundation Models
  chronos:
  tiny_time_mixer:
  moirai:
  moirai_moe:
  moment:
  timesfm:
  lagllama:
  toto:
  tabpfn:
    context_window: [10]
    forecast_window: [10]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse, mape]
  tensorboard: True