test_type: deterministic
dataset:
  name: australian_electricity_demand
  path: benchmarking_pipeline/datasets/australian_electricity_demand
  frequency: D
  split_ratio: [0.8, 0.1, 0.1]
  normalize: false
  handle_missing: interpolate
  chunks: 2

model:
  

  exponential_smoothing:
    trend: ["none", "add"]
    seasonal: ["none", "add", "mul"]
    seasonal_periods: [7]
    damped_trend: [false]
    forecast_horizon: [10]
  svr:
    kernel: ["rbf", "linear"]
    C: [0.1, 1.0, 10.0]
    epsilon: [0.01, 0.1, 0.2]
    gamma: ["scale", "auto"]
    lookback_window: [50, 100]
    random_state: [42]
    forecast_horizon: [10]
  arima:
    p: [0, 1, 2]
    d: [0, 1]
    q: [0, 1, 2]
    s: [2, 4]
    training_loss: ["mae"]
    forecast_horizon: [10]
  theta:
    sp: [1, 2, 3]
    forecast_horizon: [10]
  moirai:
    size: ["small"]
    psz: [32]
    bsz: [8]
    num_samples: [5]
    pdt: [10]
  moirai_moe:
    size: ["small"]
    psz: [32]
    bsz: [8]
    num_samples: [5]
    pdt: [10]
  toto:
    num_samples: [40]
    samples_per_batch: [40]
    prediction_length: [10]
  seasonal_naive:
    sp: [7, 14]
    forecast_horizon: [10]
  deepar:
    context_length: [20]
    num_samples: [5]
    batch_size: [8]
    epochs: [1]
    learning_rate: [0.001]
    max_prediction_length: [10]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
  tensorboard: true