test_type: deterministic
dataset:
  name: australian_electricity_demand
  path: benchmarking_pipeline/datasets/australian_electricity_demand
  frequency: D
  forecast_horizon: 5
  split_ratio: [0.8, 0.1, 0.1]
  normalize: false
  handle_missing: interpolate
  chunks: 2
model:
  # Running all models with automatic variant detection
  # Format: "model_name" - system automatically detects optimal variant based on dataset
  # Anyvariate models can handle both variants within the same implementation
  # Non-anyvariate models route to separate univariate/multivariate folders based on dataset properties
  name: [
    "random_forest", "svr", "tabpfn", "chronos", "moment", "lagllama", "timesfm", "deepar",
    "foundation_model", "base_model"
  ]

  parameters:
    tiny_time_mixer:
      prediction_length: [40]
    moment:
      model_path: ['AutonLab/MOMENT-1-large']
      context_length: [512]
      fine_tune_epochs: [0]
      batch_size: [8]
      learning_rate: [0.0001]
      prediction_length: [40]
    lagllama:
      prediction_length: [100]
      context_length: [4]
      num_samples: [5]
      batch_size: [4]
      target_cols: ['y']
    timesfm:
      per_core_batch_size: [2]
      horizon_len: [40]
      num_layers: [2]
      context_len: [2]
      use_positional_embedding: [False]
      target_cols: ['y']
    tabpfn:
      allow_large_cpu_dataset: [True]
      max_sequence_length: [32]
      prediction_length: [40]
      target_cols: ['y']
    chronos:
      model_size: ['small']
      context_length: [8]
      num_samples: [5]
      prediction_length: [40]
      target_cols: ['y']
    xgboost:
      lookback_window: [10]
      forecast_horizon: [10]
      n_estimators: [10]
      max_depth: [5]
      learning_rate: [0.1]
      random_state: [42]
      n_jobs: [-1]
      target_cols: ['y']
    prophet:
      seasonality_mode: ["additive"]
      changepoint_prior_scale: [0.05]
      seasonality_prior_scale: [10.0]
      yearly_seasonality: [false]
      weekly_seasonality: [false]
      daily_seasonality: [false]
      target_cols: ['y']
    lstm:
      units: [32]
      layers: [1]
      dropout: [0.1]
      learning_rate: [0.01, 1]
      batch_size: [32]
      epochs: [20]
      sequence_length: [10]
      target_cols: ["y"]
      loss_functions: ["mae"]
      primary_loss: ["mae"]
      forecast_horizon: [50]
    random_forest:
      lookback_window: [50, 100]
      forecast_horizon: [50]
      n_estimators: [10, 50]
      max_depth: [3, 7]
      random_state: [42]
      n_jobs: [-1]
      target_cols: ["y"]
    exponential_smoothing:
      trend: ["none", "add"]
      seasonal: ["none", "add", "mul"]
      seasonal_periods: [7]
      damped_trend: [false]
      forecast_horizon: [50]
      target_cols: ["y"]
    svr:
      kernel: ["rbf", "linear"]
      C: [0.1, 1.0, 10.0]
      epsilon: [0.01, 0.1, 0.2]
      gamma: ["scale", "auto"]
      lookback_window: [50, 100]
      forecast_horizon: [50]
      max_iter: [1000]
      random_state: [42]
      target_cols: ["y"]
    arima:
      p: [0, 1, 2]
      d: [0, 1]
      q: [0, 1, 2]
      s: [2, 4]
      maxlags: [10]
      target_cols: ["y"]
      loss_functions: ["mae"]
      primary_loss: ["mae"]
      forecast_horizon: [50]
    theta:
      sp: [1, 2, 3]
      forecast_horizon: [10]
      method: ["additive"]
      target_cols: ["y"]
      loss_functions: ["mae"]
      primary_loss: ["mae"]
    moirai:
      model_name: ["moirai"]
      size: ["small"]
      pdt: [900]
      psz: [32]
      bsz: [8]
      num_samples: [5]
      target_cols: ['y']
    moirai_moe:
      model_name: ["moirai_moe"] #, moirai_moe"] # moirai and moirai_moe come from the same model file
      size: ["small"]
      pdt: [900]
      psz: [32]
      bsz: [8]
      num_samples: [5]
      target_cols: ['y']
    toto:
      model_name: ["toto"]
      prediction_length: [900]
      num_samples: [40]
      samples_per_batch: [40]
      target_cols: ["y"]
    seasonal_naive:
      sp: [7, 14]
      forecast_horizon: [50]
      target_cols: ["y"]
    deepar:
      prediction_length: [40]
      context_length: [20]
      num_samples: [5]
      batch_size: [8]
      epochs: [1]
      learning_rate: [0.001]
      target_cols: ["y"]
    foundation_model:
      model_name: ["foundation"]
      prediction_length: [40]
      context_length: [20]
      num_samples: [5]
      batch_size: [8]
      target_cols: ["y"]
    base_model:
      model_name: ["base"]
      prediction_length: [40]
      context_length: [20]
      num_samples: [5]
      batch_size: [8]
      target_cols: ["y"]
evaluation:
  type: deterministic
  metrics: [mae, rmse] 