test_type: deterministic
tensorboard: true
dataset:
  name: australian_electricity_demand
  path: benchmarking_pipeline/datasets/australian_electricity_demand
  frequency: D
  forecast_horizon: 5
  split_ratio: [0.8, 0.1, 0.1]
  normalize: false
  handle_missing: interpolate
  chunks: 2
model:
  name: ["chronos"]
  parameters:
    Chronos:
      model_size: "small"
      context_length: 64
      num_samples: 10
      forecast_horizon: 5
evaluation:
  type: deterministic
  metrics: [mae, rmse]