# Default configuration for benchmarking pipeline

data:
  path: "data/"
  train_split: 0.8
  validation_split: 0.1
  test_split: 0.1

preprocessing:
  normalize: true
  remove_outliers: false

feature_extraction:
  method: "basic"
  n_features: 10

model:
  type: "default"
  parameters:
    learning_rate: 0.001
    batch_size: 32
    epochs: 100

evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score

logging:
  level: "INFO"
  save_path: "logs/" 