test_type: deterministic
tensorboard: true
dataset:
  name: taxi_30min
  path: benchmarking_pipeline/datasets/taxi_30min
  frequency: 30T
  forecast_horizon: 24
  split_ratio: [0.6, 0.2, 0.2]
  normalize: true
  handle_missing: interpolate
model:
  name: ARIMA
evaluation:
  type: deterministic
  metrics: [mae, rmse]