test_type: deterministic
tensorboard: true
dataset:
  name: taxi_30min
  path: benchmarking_pipeline/datasets/taxi_30min
  frequency: 30T
  forecast_horizon: 2
  split_ratio: [0.8, 0.1, 0.1]
  normalize: false
  handle_missing: interpolate
  chunks: 50
model:
  name: ["ARIMA", "ExponentialSmoothing", "RandomForest", "Theta", "XGBoost", "Prophet", "LSTM", "CrostonClassic", "SVR", "SeasonalNaive"]
  parameters:
    ARIMA:
      p: [0, 1, 2]
      d: [0, 1]
      q: [0, 1, 2]
      target_col: ["y"]
      loss_functions: ["mae"]
      primary_loss: ["mae"]
      forecast_horizon: [2]
    ExponentialSmoothing:
      trend: ["add"]
      seasonal: ["add"]
      seasonal_periods: [7]
      damped_trend: [false]
      forecast_horizon: [2]
    LSTM:
      units: [32]
      layers: [1]
      dropout: [0.1]
      learning_rate: [0.01, 0.1, 1]
      batch_size: [32]
      epochs: [20]
      sequence_length: [10]
      target_col: ["y"]
      loss_functions: ["mae"]
      primary_loss: ["mae"]
      forecast_horizon: [2]
    RandomForest:
      lookback_window: [10, 20]
      forecast_horizon: [2]
      n_estimators: [10, 50]
      max_depth: [3, 7]
      random_state: [42]
      n_jobs: [-1]
    Theta:
      sp: [1, 2, 3, 4]
      forecast_horizon: [10]
      seasonality_mode: ["additive"]
    XGBoost:
      lookback_window: [10]
      forecast_horizon: [2]
      n_estimators: [50, 100]
      max_depth: [5, 10]
      learning_rate: [0.1, 0.5]
      random_state: [42]
      n_jobs: [-1]
    Prophet:
      seasonality_mode: ["additive"]
      changepoint_prior_scale: [0.05, 0.1, 0.5]
      seasonality_prior_scale: [10.0, 20.0, 50.0]
      yearly_seasonality: [true]
      weekly_seasonality: [true]
      daily_seasonality: [false]
    CrostonClassic:
      alpha: [0.1, 0.5, 1]
      target_col: ["y"]
      loss_functions: ["mae"]
      primary_loss: ["mae"]
      forecast_horizon: [2]
    SVR:
      kernel: ["rbf", "poly", "sigmoid"]
      C: [1.0]
      epsilon: [0.1]
      lookback_window: [10, 20]
      forecast_horizon: [2]
      random_state: [42]
    SeasonalNaive:
      sp: [7, 14]
      forecast_horizon: [2]
evaluation:
  type: deterministic
  metrics: [mae, rmse]