test_type: deterministic
tensorboard: true
dataset:
  name: australian_electricity_demand
  path: benchmarking_pipeline/datasets/australian_electricity_demand
  frequency: 30T
  forecast_horizon: 10
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 2
model:
  name: ["exponential_smoothing"]
  parameters:
    ExponentialSmoothing:
      trend: ["none", "add"]
      seasonal: ["none", "add", "mul"]
      seasonal_periods: [7]
      damped_trend: [false, true]
      forecast_horizon: [10]
evaluation:
  type: deterministic
  metrics: [mae, rmse] 