test_type: deterministic
dataset:
  name: borealis
  path: benchmarking_pipeline/datasets/borealis
  frequency: 30T
  forecast_horizon: 50
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 1
model:
  name: ["arima"]
  search_method: "bayesian"  # Use Bayesian optimization
  parameters:
    ARIMA:
      search_iterations: 20
      p: {"min": 0, "max": 6, "type": "int"}
      d: {"min": 0, "max": 6, "type": "int"}
      q: {"min": 0, "max": 6, "type": "int"}
      target_col: ["y"]
      loss_functions: ["mae"]
      primary_loss: ["mae"]
      forecast_horizon: [50]
    ExponentialSmoothing:
      search_iterations: 10
      trend: ["none", "add", "mul"]
      seasonal: ["none", "add", "mul"]
      seasonal_periods: {"min": 7, "max": 96, "type": "int"}
      # damped_trend: [false, true]
      forecast_horizon: [50]
    LSTM:
      search_iterations: 5
      units: 16
      layers: 1
      learning_rate: {"min": 0.001, "max": 1.0, "type": "float"}
      sequence_length: {"min": 50, "max": 100, "type": "int"}
      target_col: ["y"]
      loss_functions: ["mae"]
      primary_loss: ["mae"]
      forecast_horizon: [50]
    RandomForest:
      search_iterations: 10
      lookback_window: {"min": 50, "max": 100, "type": "int"}
      forecast_horizon: [50]
      n_estimators: {"min": 10, "max": 200, "type": "int"}
      max_depth: {"min": 3, "max": 7, "type": "int"}
      min_samples_split: {"min": 2, "max": 7, "type": "int"}
      min_samples_leaf: {"min": 1, "max": 5, "type": "int"}
      random_state: [42]
      n_jobs: [-1]
    Theta:
      search_iterations: 5
      sp: {"min": 1, "max": 96, "type": "int"}
      forecast_horizon: [10]
      method: ["additive"]
    XGBoost:
      search_iterations: 10
      lookback_window: {"min": 20, "max": 100, "type": "int"}
      forecast_horizon: [50]
      n_estimators: {"min": 10, "max": 50, "type": "int"}
      max_depth: {"min": 3, "max": 10, "type": "int"}
      learning_rate: {"min": 0.01, "max": 1.0, "type": "float"}
      random_state: [42]
      n_jobs: [-1]
    Prophet:
      search_iterations: 10
      seasonality_mode: ["additive", "multiplicative"]
      changepoint_prior_scale: {"min": 0.001, "max": 1.0, "type": "float"}
      seasonality_prior_scale: {"min": 0.01, "max": 20.0, "type": "float"}
      yearly_seasonality: [true, false]
      weekly_seasonality: [true, false]
      daily_seasonality: [true, false]
    CrostonClassic:
      search_iterations: 10
      alpha: {"min": 0.01, "max": 1.0, "type": "float"}
      target_col: ["y"]
      loss_functions: ["mae"]
      primary_loss: ["mae"]
      forecast_horizon: [50]
    SVR:
      search_iterations: 10
      kernel: ["rbf", "poly", "linear"]
      C: {"min": 0.1, "max": 10.0, "type": "float"}
      # epsilon: {"min": 0.01, "max": 0.5, "type": "float"}
      # gamma: {"min": 0.01, "max": 0.5, "type": "float"}
      lookback_window: {"min": 50, "max": 100, "type": "int"}
      forecast_horizon: [50]
      random_state: [42]
    SeasonalNaive:
      search_iterations: 10
      sp: {"min": 7, "max": 96, "type": "int"}
      forecast_horizon: [50]
evaluation:
  type: deterministic
  metrics: [mae, rmse] 