test_type: regularly_sampled
dataset:
  name: saugeenday
  path: datasets/saugeenday
  frequency: D
  forecast_horizon: 144
  split_ratio: [0.6, 0.2, 0.2]
  normalize: true
  handle_missing: interpolate
model:
  name: ["ARIMA", "ExponentialSmoothing"]
  parameters:
    ARIMA:
      p: [0, 1, 2]
      d: [0, 1]
      q: [0, 1, 2]
    ExponentialSmoothing:
      trend: [add, mul]
      seasonal: [add, mul]
      seasonal_periods: [7, 14, 28]
      damped_trend: [True, False]
    LSTM:
      units: 100
      layers: 1
      learning_rate: [0.001, 0.01, 0.1]
      batch_size: 32
      epochs: 10
      dropout: 0.1
      optimizer: adam
      loss: mse
      metrics: [mae, rmse]
      verbose: 1
      validation_split: 0.2
      callbacks: [EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)]

evaluation:
  type: deterministic
  metrics: [mae, rmse]