test_type: deterministic
dataset:
  name: azure_vm_traces_2017
  path: benchmarking_pipeline/datasets/azure_vm_traces_2017
  frequency: D
  forecast_horizon: 5
  split_ratio: [0.8, 0.1, 0.1]
  normalize: false
  handle_missing: interpolate
  chunks: 2
model:
  name: ["moirai_moe"]
  parameters:
    Moirai_MoE:
      model_name: ["moirai_moe"]
      size: ["small"]
      pdt: [200]
      ctx: [10]
      psz: [8]
      bsz: [8]
      test: [200]
      num_samples: [5]
evaluation:
  type: deterministic
  metrics: [mae, rmse] 