test_type: regularly_sampled
tensorboard: true
dataset:
  name: australian_electricity_demand
  path: benchmarking_pipeline/datasets/australian_electricity_demand
  frequency: 30T
  forecast_horizon: 5
  split_ratio: [0.8, 0.1, 0.1]
  normalize: false
  handle_missing: interpolate
  chunks: 2
model:
  name: ["random_forest"]
  parameters:
    RandomForest:
      lookback_window: [10, 20]
      forecast_horizon: [5]
      n_estimators: [10, 50]
      max_depth: [3, 7]
      random_state: [42]
      n_jobs: [1]
evaluation:
  type: deterministic
  metrics: [mae, rmse] 