test_type: regularly_sampled
tensorboard: true
dataset:
  name: saugeenday
  path: datasets/saugeenday
  frequency: D
  forecast_horizon: 144
  split_ratio: [0.6, 0.2, 0.2]
  normalize: true
  handle_missing: interpolate
model:
  name: ["ARIMA", "ExponentialSmoothing"]
  parameters:
    ARIMA:
      p: [0, 1, 2]
      d: [0, 1]
      q: [0, 1, 2]
    ExponentialSmoothing:
      trend: [add, mul]
      seasonal: [add, mul]
evaluation:
  type: deterministic
  metrics: [mae, rmse]