test_type: deterministic
dataset:
  name: australian_electricity_demand
  path: benchmarking_pipeline/datasets/australian_electricity_demand
  frequency: D
  forecast_horizon: 5
  split_ratio: [0.8, 0.1, 0.1]
  normalize: false
  handle_missing: interpolate
  chunks: 2
model:
  name: ["tabPFN"]
  parameters:
    TabPFN:
      n_ensemble_configs: 32
      device: "cpu"
      forecast_horizon: 5
      target_col: "y"
evaluation:
  type: deterministic
  metrics: [mae, rmse]