test_type: deterministic
tensorboard: true
dataset:
  name: china_air_quality
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3

model:
  lstm:
    units: [64]
    layers: [2]
    dropout: [0.1]
    learning_rate: [0.001]
    batch_size: [64]
    epochs: [15]
    sequence_length: [24]
    training_loss: ["mae"]
    forecast_horizon: [10]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
