test_type: deterministic
tensorboard: true
dataset:
  name: bdg-2_bear
  split_ratio: [0.8, 0.1, 0.1]
  normalize: True
  handle_missing: interpolate
  chunks: 3

model:
  moirai_moe:
    size: ["small", "base"]  # Try both small and base for better performance
    psz: [16, 32, 64]       # Try different patch sizes for better feature extraction
    bsz: [8]                 # Keep working batch size
    num_samples: [5, 10]     # Try more samples for robust predictions
    pdt: [900]               # Keep working commit prediction length

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
