test_type: deterministic
tensorboard: true
dataset:
  name: bdg-2_bear
  path: benchmarking_pipeline/datasets/bdg-2_bear
  frequency: 30T
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3


model:
  chronos:
    model_size: ['small']
    context_length: [8]
    num_samples: [5]
    prediction_length: [10]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
