test_type: deterministic
tensorboard: true
dataset:
  name: bdg-2_bear
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3

model:
  lstm:
    units: [32]
    layers: [1]
    dropout: [0.1]
    learning_rate: [0.01]
    batch_size: [32]
    epochs: [20]
    sequence_length: [10]
    training_loss: ["mae"]
    forecast_horizon: [10]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
