test_type: deterministic
tensorboard: true
dataset:
  name: bdg-2_bear
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3

model:
  lagllama:
    context_length: [128]
    num_samples: [100]
    batch_size: [1]
    prediction_length: [30]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
