test_type: deterministic
tensorboard: true
dataset:
  name: bdg-2_bear
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3

model:
  timesfm:
    per_core_batch_size: [2]
    horizon_len: [10]
    num_layers: [2]
    context_len: [2]
    use_positional_embedding: [False]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
