test_type: deterministic
tensorboard: true
dataset:
  name: china_air_quality
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3

model:
  svr:
    lookback_window: [50]
    C: [1.0]
    epsilon: [0.1]
    kernel: ["rbf"]
    gamma: ["scale"]
    n_jobs: [-1]
    forecast_horizon: [10]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
