test_type: deterministic
tensorboard: true
dataset:
  name: bdg-2_bear
  path: benchmarking_pipeline/datasets/bdg-2_bear
  frequency: 30T
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3
  target_cols: ['bdg2_bear_metric']

model:
  arima:
    p: [0, 1, 2]      # Working univariate config from 3 days ago
    d: [0, 1]         # Working univariate config from 3 days ago  
    q: [0, 1, 2]      # Working univariate config from 3 days ago
    s: [2, 4]         # Working univariate config from 3 days ago
    training_loss: ["mae"]
    forecast_horizon: [10]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
