test_type: deterministic
tensorboard: true
dataset:
  name: bdg-2_bear
  path: benchmarking_pipeline/datasets/bdg-2_bear
  frequency: 30T
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3
  target_cols: ['bdg2_bear_metric']

model:
  arima:
    p: [1, 2, 3, 4]
    d: [0, 1, 2]
    q: [1, 2, 3, 4]
    s: [1, 24, 48]  # Try different seasonality periods to capture cycles
    training_loss: ["mae"]
    forecast_horizon: [10]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
