test_type: deterministic
tensorboard: true
dataset:
  name: bdg-2_bear
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3

model:
  tabpfn:
    allow_large_cpu_dataset: [True]
    max_sequence_length: [32]
    prediction_length: [10]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
