test_type: deterministic
tensorboard: true
dataset:
  name: bdg-2_bear
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3

model:
  tiny_time_mixer:
    forecast_horizon: [10]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
