test_type: deterministic
tensorboard: true
dataset:
  name: bdg-2_bear
  split_ratio: [0.8, 0.1, 0.1]
  normalize: True
  handle_missing: interpolate
  chunks: 3

model:
  moirai:
evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
