test_type: deterministic
tensorboard: true
dataset:
  name: bdg-2_bear
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3

model:
  prophet:
    seasonality_mode: ["additive"]
    changepoint_prior_scale: [0.05]
    seasonality_prior_scale: [10.0]
    yearly_seasonality: [true]
    weekly_seasonality: [true]
    daily_seasonality: [false]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
