test_type: deterministic
tensorboard: true
dataset:
  name: bdg-2_bear
  path: benchmarking_pipeline/datasets/bdg-2_bear
  frequency: 30T
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3

model:
  random_forest:
    lookback_window: [50]
    n_estimators: [50]
    max_depth: [7]
    random_state: [42]
    n_jobs: [-1]
    forecast_horizon: [10]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
