test_type: deterministic
tensorboard: true
dataset:
  name: bdg-2_bear
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3

model:
  toto:
    num_samples: [10]
    samples_per_batch: [5]
    prediction_length: [10]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
