test_type: deterministic
tensorboard: true
dataset:
  name: bdg-2_bear
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3


model:
  chronos:
    model_size: ['tiny', 'small']  # Try different model sizes
    context_length: [8, 16, 32]   # Try different context lengths
    num_samples: [5, 10]           # Try different sample counts
    prediction_length: [64]        # Use Chronos's recommended maximum

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
