test_type: deterministic
tensorboard: true
dataset:
  name: china_air_quality
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3

model:
  xgboost:
    lookback_window: [20]
    n_estimators: [10]
    max_depth: [6]
    learning_rate: [0.1]
    subsample: [0.8]
    colsample_bytree: [0.8]
    random_state: [42]
    n_jobs: [1]
    forecast_horizon: [10]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
