test_type: deterministic
tensorboard: true
dataset:
  name: bdg-2_bear
  split_ratio: [0.8, 0.1, 0.1]
  normalize: true
  handle_missing: interpolate
  chunks: 3

model:
  xgboost:
    lookback_window: [30]
    n_estimators: [200]
    max_depth: [4]
    learning_rate: [0.05]
    subsample: [0.9]
    colsample_bytree: [0.9]
    random_state: [42]
    n_jobs: [-1]
    forecast_horizon: [10]

evaluation:
  type: deterministic
  metrics: [mae, mase, rmse]
