test_type: deterministic
dataset:
  name: australian_electricity_demand
  path: benchmarking_pipeline/datasets/australian_electricity_demand
  frequency: D
  forecast_horizon: 5
  split_ratio: [0.8, 0.1, 0.1]
  normalize: false
  handle_missing: interpolate
  chunks: 2
model:
  name: ["timesfm"]
  parameters:
    TimesFM:
      model_path: "google/timesfm-1.0-200m"
      forecast_horizon: 5
evaluation:
  type: deterministic
  metrics: [mae, rmse]