test_type: deterministic
dataset:
  name: australian_electricity_demand
  path: benchmarking_pipeline/datasets/australian_electricity_demand
  frequency: D
  forecast_horizon: 5
  split_ratio: [0.8, 0.1, 0.1]
  normalize: false
  handle_missing: interpolate
  chunks: 2
model:
  name: ["toto"]
  parameters:
    Toto:
      model_name: ["toto"]
      self.prediction_length: [4]
      self.num_samples: [4]
      self.samples_per_batch: [4]
evaluation:
  type: deterministic
  metrics: [mae, rmse] 