test_type: regularly_sampled
tensorboard: true
dataset:
  name: bdg-2_bear
  path: benchmarking_pipeline/datasets/bdg-2_bear
  frequency: H
  forecast_horizon: 10
  split_ratio: [0.8, 0.1, 0.1]
  normalize: false
  handle_missing: interpolate
  chunks: 2
model:
  name: ["ARIMA", "ExponentialSmoothing", "RandomForest", "XGBoost", "Prophet", "LSTM", "CrostonClassic", "DeepAR", "SVR", "SeasonalNaive"]
  parameters:
    ARIMA:
      p: [0, 1, 2]
      d: [0, 1]
      q: [0, 1, 2]
      target_col: ["y"]
      loss_functions: ["mae"]
      primary_loss: ["mae"]
      forecast_horizon: [10]
    ExponentialSmoothing:
      trend: ["add"]
      seasonal: ["add"]
      seasonal_periods: [7]
      damped_trend: [false]
      forecast_horizon: [10]
    LSTM:
      units: [32]
      layers: [1]
      dropout: [0.1]
      learning_rate: [0.01, 0.1, 1]
      batch_size: [32]
      epochs: [20]
      sequence_length: [20]
      target_col: ["y"]
      loss_functions: ["mae"]
      primary_loss: ["mae"]
      forecast_horizon: [10]
    RandomForest:
      lookback_window: [10, 20]
      forecast_horizon: [10]
      n_estimators: [10, 50]
      max_depth: [3, 7]
      random_state: [42]
      n_jobs: [-1]
    Theta:
      sp: [1, 2]
      forecast_horizon: [10]
    XGBoost:
      lookback_window: [10]
      forecast_horizon: [10]
      n_estimators: [50, 100]
      max_depth: [5, 10]
      learning_rate: [0.1, 0.5]
      random_state: [42]
      n_jobs: [-1]
    Prophet:
      seasonality_mode: ["additive", "multiplicative"]
      changepoint_prior_scale: [0.05]
      seasonality_prior_scale: [10.0]
      yearly_seasonality: [false, true]
      weekly_seasonality: [false, true]
      daily_seasonality: [false, true]
    CrostonClassic:
      alpha: [0.1, 0.5, 1]
      target_col: ["y"]
      loss_functions: ["mae"]
      primary_loss: ["mae"]
      forecast_horizon: [10]
    DeepAR:
      hidden_size: [2]
      rnn_layers: [2, 3]
      dropout: [0.1]
      batch_size: [1]
      learning_rate: [0.001]
      target_col: ["y"]
      forecast_horizon: [10]
      epochs: [1]
      num_workers: [4]
    SVR:
      kernel: ["rbf", "poly", "sigmoid"]
      C: [1.0]
      epsilon: [0.1]
      lookback_window: [10, 20]
      forecast_horizon: [10]
      random_state: [42]
    SeasonalNaive:
      sp: [7, 14]
      forecast_horizon: [5]
evaluation:
  type: deterministic
  metrics: [mae, rmse]